package com.shock.herogrind.world.internal.domain;

public enum WorldEventType {
  HERO_IDLE,
  HERO_ENTERED_DUNGEON,
  HERO_STARTED_ROAMING,
  HERO_STARTED_ENCOUNTER,
  HERO_ENDED_ENCOUNTER,
  COMBAT_ACTION,
  HERO_DIED,
  HERO_GHOST_RESURRECTING,
  HERO_GHOST_TRAVELING,
  HERO_RESURRECTED,
}
